//king loves swift
print("k        k         d")
print("k      k           d")
print("k    k             d")
print("k  k               d")
print("kk                 d")
print("k  k               d")
print("k    k             d")
print("k    k             d")
print("k      k           d")
print("k        k         d")